mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('login/', include('log_reg_app.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'polls'
from .views import ChoiseViewSet
from rest_framework import renderers

choice_list = ChoiseViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    path('index/', views.list, name='index'),
    path('', views.d_log_in, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('delete_question/', views.delete_question, name='delete_question'),
    path('delete_messages/', views.DeleteMessages.as_view(), name='delete_messages'),
    path('add_new/', views.add_new, name='add_new'),
    path('new-q/', views.new_q, name='new-q'),
    path('questions/', views.QuestionList.as_view()),
    path('questions/<int:pk>/', views.QuestionDetail.as_view()),
    path('choices/', choice_list),
    path('choices/<int:pk>/', views.ChoiceDetail.as_view(), name='choice'),
    path('api/', views.api_root),
]


# snippet_detail = SnippetViewSet.as_view({
#     'get': 'retrieve',
#     'put': 'update',
#     'patch': 'partial_update',
#     'delete': 'destroy'
# })
urlpatterns = format_suffix_patterns(urlpatterns)

mysite/polls/models.py
import datetime
from django.forms import widgets, DateField
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    # datpub_date = fields.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    # pub_date = DateField(initial=datetime.date.today, widget=widgets.DateInput(attrs={'type': 'date'}))
    
    def was_published_recently(self):
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# class User(models.Model):
#     username = models.CharField(max_length=200)
#     password = models.CharField(max_length=200)

mysite/polls/forms.py
from django import forms
from django.utils import timezone
from .views import Question
from django.contrib.auth.models import User
from django.core import validators
import datetime
import django.contrib.admin.widgets



class DateInput(forms.DateInput):
    input_type = 'date' 
    
def no_curse(value):
    cs = ('shit', 'fuck')
    print("CHECKIIIIIIIIIIIING")
    print("value=", value)
    for c in cs:
        if c in value:
            raise forms.ValidationError("Name should not contain curses")


class NewQuestionForm(forms.ModelForm):
    CURSES = ('shit','fuck')
    question_text = forms.CharField(label='question_text', max_length=100, validators=[validators.MinLengthValidator(5)])
    pub_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'], initial=timezone.now(), widget=forms.widgets.DateTimeInput(attrs={'type': 'datetime'}))
    
    # pub_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M']
    # , initial=timezone.now()
    # , widget=django.contrib.admin.widgets.AdminSplitDateTime())

    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']

    def clean(self):
        # super(NewQuestionForm, self).clean()
        question_text  = self.cleaned_data.get('question_text')
        for c in NewQuestionForm.CURSES:
            if c in question_text:
                raise forms.ValidationError("Name should not contain curses")
        return self.cleaned_data

class DeleteMessagesForm(forms.Form):
    questions = forms.ChoiceField(
        widget = forms.CheckboxSelectMultiple,
        choices= Question.objects.values_list('id','question_text')
    )


class UserForm(forms.ModelForm):
    username = forms.CharField(label='username', max_length=100, validators=[validators.MinLengthValidator(5)])
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    
    # pub_date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M']
    # , initial=timezone.now()
    # , widget=django.contrib.admin.widgets.AdminSplitDateTime())

    class Meta:
        model = User
        fields = ['username', 'password']

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.views import generic,View
from django.utils import timezone
from .models import Question, Choice
from log_reg_app.models import LoginUser

from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser

from rest_framework import status, mixins
from rest_framework.decorators import api_view
from rest_framework.response import Response
from  rest_framework import generics
from rest_framework.views import APIView
import datetime


from .serializers import QuestionSerializer, ChoiceSerializer
from .forms import NewQuestionForm, DeleteMessagesForm, UserForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User


def d_log_in(request):
    if request.method == 'POST':
        # u = User.objects.get(username='admin')
        # u.set_password('1234')
        # u.save()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if user.get_short_name() is not None:
                request.session['username'] = user.get_short_name()
            else:
                request.session['username'] = user.get_username()
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            msg = 'User not found'
            form = UserForm()
            return render(request, 'polls/login.html',{'form': form, 'msg': msg})
    else:
        form = UserForm()
        return render(request, 'polls/login.html',{'form': form})
        
    
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:login'))

def add_new(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    d = datetime.timedelta
    form = NewQuestionForm()
    return render(request, 'polls/name.html', {'form': form})
  

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]
    
class DeleteMessages(View):
    template_name = 'polls/delete_messages.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('polls:login'))
        form = DeleteMessagesForm()
        return render(request, 'polls/delete_messages.html', {'form': form})

    
class DetailView(generic.DetailView):
    template_name = 'polls/detail.html'
    model = Question

class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Question

def list(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))

    questions = Question.objects.all()
    return HttpResponse(render(request,'polls/index.html',{'latest_question_list': questions, "username" : request.user.username}))
    

def detail(request, question_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    question = get_object_or_404(Question, pk=question_id)
    return HttpResponse(render(request,'polls/detail.html',{'question': question}))


def results(request, question_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

    
def vote(request, question_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        


def new_q(request):
    form = NewQuestionForm(request.POST)
        # check whether it's valid:
    if form.is_valid():
        question_text = form.cleaned_data['question_text']
        pub_date = form.cleaned_data['pub_date']
        Question.objects.create(question_text=question_text, pub_date=pub_date)
    else:
        pass
    return HttpResponseRedirect(reverse('polls:index'))

def delete_question(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('polls:login'))
    if request.method == 'POST':
    
        form = DeleteMessagesForm(request.POST)
        if form.is_valid():
            q_for_delete=form.cleaned_data['questions']
            print("q_for_delete: ",q_for_delete)
            for q in q_for_delete:
                try:
                    question = get_object_or_404(Question, pk=q)
                    question.delete()
            
                except:
                    pass
            
   
    return HttpResponseRedirect(reverse('polls:index'))


# API

from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser

@api_view(['GET','POST'])
def question_list(request, format=None):
    """
    List all code questions, or create a new snippet.
    """
    if request.method == 'GET':
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = QuestionSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET','POST','PUT'])
@csrf_exempt
def question_detail(request, pk, format=None):
    """
    Retrieve, update or delete a question.
    """
    try:
        request.session['username']='DANNY'

        question = Question.objects.get(pk=pk)
    except Question.DoesNotExist:
        return Response(status=404)
    if request.method == 'GET':
        serializer = QuestionSerializer(question)
        return JsonResponse(serializer.data)
    elif request.method == 'PUT':
        data = JSONParser().parse(request)
        serializer = QuestionSerializer(question, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        question.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class QuestionList(generics.ListCreateAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

# class QuestionList(mixins.ListModelMixin,
#                   mixins.CreateModelMixin,
#                   generics.GenericAPIView):
#     queryset = Question.objects.all()
#     serializer_class = QuestionSerializer

#     def get(self, request, *args, **kwargs):
#         return self.list(request, *args, **kwargs)


#     def post(self, request, *args, **kwargs):
#         return self.create(request, *args, **kwargs)


# class QuestionDetail(mixins.RetrieveModelMixin, mixins.DestroyModelMixin, mixins.UpdateModelMixin, APIView):
#     """
#     Retrieve, update or delete a snippet instance.
#     """
#     def get_object(self, pk):
#         try:
#             return Question.objects.get(pk=pk)
#         except Question.DoesNotExist:
#             raise Http404

#     def get(self, request, pk, format=None):
#         question = self.get_object(pk)
#         serializer = QuestionSerializer(question)
#         return Response(serializer.data)

#     def put(self, request, pk, format=None):
#         question = self.get_object(pk)
#         serializer = QuestionSerializer(question, data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

#     def delete(self, request, pk, format=None):
#         question = self.get_object(pk)
#         question.delete()
#         return Response(status=status.HTTP_204_NO_CONTENT)
class QuestionDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

class ChoiceList(generics.ListCreateAPIView):
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer


class ChoiceDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer


@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'questions': reverse('questions', request=request, format=format),
        'choices': reverse('choices', request=request, format=format)
    })



from rest_framework import viewsets

class ChoiseViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list` and `retrieve` actions.
    """
    queryset = Choice.objects.all()
    serializer_class = ChoiceSerializer

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{%  include 'polls/side_bar.html' %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<head>
</head>
<body>
    <div id="header">
        Polls app
    </div>
    
    <div id="main_content">
        {% block content %}{% endblock %}
    </div>
    
    <div id="footer">
        powered by django
    </div>
</body>
</html>

mysite/polls/templates/polls/basenobar.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<head>
</head>
<body>
    <div id="header">
        Polls app
    </div>
    
    <div id="main_content">
        {% block content %}{% endblock %}
    </div>
    
    <div id="footer">
        powered by django
    </div>
</body>
</html>

mysite/polls/templates/polls/delete_messages.html
{% extends 'polls\base.html' %}

{% block content%}

<p>
    <ul>
    <form action="{% url 'polls:delete_question' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="delete question">
    </ul>
    {% comment %} {% else %}
        <p>No polls are available.</p>
    {% endif %} {% endcomment %}
</p>
{% endblock %}

mysite/polls/templates/polls/detail.html
{% extends 'polls\base.html' %}

{% comment %} <!DOCTYPE html>
<html>
<body> {% endcomment %}
{% block content%}
<p>
    <h1>{{ question.question_text }}</h1>
    <p>Published date: {{question.pub_date}}</p>
    <ul>
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.question_text }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                {% if request.session.username %}<p><strong>Hello {{ request.session.username }}</strong></p>{%else%}<p><strong>No user name</strong></p>{% endif %}
                {% for choice in question.choice_set.all %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Vote">
        </form>
    </ul>
</p>
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls\base.html' %}

{% comment %} <!DOCTYPE html>
<html>
<body> {% endcomment %}
{% block content %}
<h1>index</h1>
<p>
    {% if request.session.username %}<p><strong>Hello {{ request.session.username }}</strong></p>{%else%}<p><strong>No user name</strong></p>{% endif %}
    {% if latest_question_list %}
    <ul>
    <form action="{% url 'polls:delete_question' %}" method="post">
        {% csrf_token %}
        <fieldset>
        {% for question in latest_question_list %}
            <li> 
                <input type="checkbox" name="q" id="question{{ forloop.counter }}" value="{{ question.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </fieldset>
        <input type="submit" value="delete question">
    </form>
    {% else %}
        <p>No polls are available.</p>
    {% endif %} 
    {% comment %} <p><a href="{% url 'polls:add_new' %}"> Add a new question </a></p>
    <p><a href="{% url 'polls:delete_messages' %}">Delete Questions </a></p> {% endcomment %}
{% endblock%}
</p>

{% comment %} </body>
</html> {% endcomment %}

mysite/polls/templates/polls/login.html
{% extends 'polls\base.html' %}

{% comment %} <!DOCTYPE html>
<html>
<body> {% endcomment %}
{% block content%}
<p>Hi there </p>
<form action="{% url 'polls:login'%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="login">
</form>
{% if msg %}<p style={'color':'white'>}> {{ msg }}</p> {% endif %}
{%endblock%}

mysite/polls/templates/polls/name.html
{% extends 'polls\base.html' %}

{% comment %} <!DOCTYPE html>
<html>
<body> {% endcomment %}
{% if request.session.username %}<p><strong>Hello {{ request.session.username }}</strong></p>{%else%}<p><strong>No user name</strong></p>{% endif %}
{% block content%}

<form action="{% url 'polls:new-q'%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="new-q">
</form>
{%endblock%}

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<body>

<h1>{{ question.question_text }}</h1>
{% if request.session.username %}<p><strong>Hello {{ request.session.username }}</strong></p>{%else%}<p><strong>No user name</strong></p>{% endif %}

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>

mysite/polls/templates/polls/side_bar.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/side_bar.css' %}">


<div id="main" class="main">
    <a href="#">About</a>
    <a href="#">Services</a>
    <a href="#">Clients</a>
    <a href="#">Contact</a>
  </div>
  
    
  <!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->
  <div id="mySidenav" class="sidenav">
    <a href="{% url 'polls:index' %}">index</a>
    <a href="{% url 'polls:add_new' %}">add question</a>
    <a href="{% url 'polls:delete_messages' %}">delete questions</a>
    <br/>
    <a href="{% url 'polls:logout' %}">log out</a>
  </div>